explorer/urls.py
from django.urls import path, re_path

from explorer.views import (
    QueryView,
    CreateQueryView,
    PlayQueryView,
    DeleteQueryView,
    ListQueryView,
    ListQueryLogView,
    DownloadFromSqlView,
    DownloadQueryView,
    StreamQueryView,
    EmailCsvQueryView,
    SchemaView,
    format_sql,
)

urlpatterns = [
    path(
        '<int:query_id>/', QueryView.as_view(), name='query_detail'
    ),
    path(
        '<int:query_id>/download', DownloadQueryView.as_view(),
        name='download_query'
    ),
    path(
        '<int:query_id>/stream', StreamQueryView.as_view(),
        name='stream_query'
    ),
    path('download', DownloadFromSqlView.as_view(), name='download_sql'),
    path(
        '<int:query_id>/email_csv', EmailCsvQueryView.as_view(),
        name='email_csv_query'
    ),
    path(
        '<int:pk>/delete', DeleteQueryView.as_view(), name='query_delete'
    ),
    path('new/', CreateQueryView.as_view(), name='query_create'),
    path('play/', PlayQueryView.as_view(), name='explorer_playground'),
    re_path(
        r'schema/(?P<connection>.+)$', SchemaView.as_view(),
        name='explorer_schema'
    ),
    path('logs/', ListQueryLogView.as_view(), name='explorer_logs'),
    path('format/', format_sql, name='format_sql'),
    path('', ListQueryView.as_view(), name='explorer_index'),
]

explorer/models.py
import logging
from time import time

from django.conf import settings
from django.db import models, DatabaseError, transaction
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from explorer import app_settings
from explorer.utils import (
    passes_blacklist,
    swap_params,
    extract_params,
    shared_dict_update,
    get_s3_bucket,
    get_params_for_url,
    get_valid_connection
)

MSG_FAILED_BLACKLIST = "Query failed the SQL blacklist: %s"


logger = logging.getLogger(__name__)


class Query(models.Model):
    title = models.CharField(max_length=255)
    sql = models.TextField(blank=False, null=False)
    description = models.TextField(blank=True)
    created_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    last_run_date = models.DateTimeField(auto_now=True)
    snapshot = models.BooleanField(
        default=False,
        help_text=_("Include in snapshot task (if enabled)")
    )
    connection = models.CharField(
        blank=True,
        max_length=128,
        default='',
        help_text=_(
            "Name of DB connection (as specified in settings) to use for "
            "this query."
            "Will use EXPLORER_DEFAULT_CONNECTION if left blank"
        )
    )

    def __init__(self, *args, **kwargs):
        self.params = kwargs.get('params')
        kwargs.pop('params', None)
        super().__init__(*args, **kwargs)

    class Meta:
        ordering = ['title']
        verbose_name = _('Query')
        verbose_name_plural = _('Queries')

    def __str__(self):
        return str(self.title)

    def get_run_count(self):
        return self.querylog_set.count()

    def avg_duration(self):
        return self.querylog_set.aggregate(
            models.Avg('duration')
        )['duration__avg']

    def passes_blacklist(self):
        return passes_blacklist(self.final_sql())

    def final_sql(self):
        return swap_params(self.sql, self.available_params())

    def execute_query_only(self):
        return QueryResult(
            self.final_sql(), get_valid_connection(self.connection)
        )

    def execute_with_logging(self, executing_user):
        ql = self.log(executing_user)
        ret = self.execute()
        ql.duration = ret.duration
        ql.save()
        return ret, ql

    def execute(self):
        ret = self.execute_query_only()
        ret.process()
        return ret

    def available_params(self):
        """
        Merge parameter values into a dictionary of available parameters

        :return: A merged dictionary of parameter names and values.
                 Values of non-existent parameters are removed.
        :rtype: dict
        """
        p = extract_params(self.sql)
        if self.params:
            shared_dict_update(p, self.params)
        return p

    def get_absolute_url(self):
        return reverse("query_detail", kwargs={'query_id': self.id})

    @property
    def params_for_url(self):
        return get_params_for_url(self)

    def log(self, user=None):
        if user:
            if user.is_anonymous:
                user = None
        ql = QueryLog(
            sql=self.final_sql(),
            query_id=self.id,
            run_by_user=user,
            connection=self.connection
        )
        ql.save()
        return ql

    @property
    def shared(self):
        return self.id in set(
            sum(app_settings.EXPLORER_GET_USER_QUERY_VIEWS().values(), [])
        )

    @property
    def snapshots(self):
        if app_settings.ENABLE_TASKS:
            b = get_s3_bucket()
            keys = b.list(prefix=f'query-{self.id}/snap-')
            keys_s = sorted(keys, key=lambda k: k.last_modified)
            return [
                SnapShot(
                    k.generate_url(expires_in=0, query_auth=False),
                    k.last_modified
                ) for k in keys_s
            ]


class SnapShot:

    def __init__(self, url, last_modified):
        self.url = url
        self.last_modified = last_modified


class QueryLog(models.Model):

    sql = models.TextField(blank=True)
    query = models.ForeignKey(
        Query,
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    run_by_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.CASCADE
    )
    run_at = models.DateTimeField(auto_now_add=True)
    duration = models.FloatField(blank=True, null=True)  # milliseconds
    connection = models.CharField(blank=True, max_length=128, default='')

    @property
    def is_playground(self):
        return self.query_id is None

    class Meta:
        ordering = ['-run_at']


class QueryResult:

    def __init__(self, sql, connection):

        self.sql = sql
        self.connection = connection

        cursor, duration = self.execute_query()

        self._description = cursor.description or []
        self._data = [list(r) for r in cursor.fetchall()]
        self.duration = duration

        cursor.close()

        self._headers = self._get_headers()
        self._summary = {}

    @property
    def data(self):
        return self._data or []

    @property
    def headers(self):
        return self._headers or []

    @property
    def header_strings(self):
        return [str(h) for h in self.headers]

    def _get_headers(self):
        return [
            ColumnHeader(d[0]) for d in self._description
        ] if self._description else [ColumnHeader('--')]

    def _get_numerics(self):
        if hasattr(self.connection.Database, "NUMBER"):
            return [
                ix for ix, c in enumerate(self._description)
                if hasattr(c, 'type_code') and c.type_code in self.connection.Database.NUMBER.values
            ]
        elif self.data:
            d = self.data[0]
            return [
                ix for ix, _ in enumerate(self._description)
                if not isinstance(d[ix], str) and str(d[ix]).isnumeric()
            ]
        return []

    def _get_transforms(self):
        transforms = dict(app_settings.EXPLORER_TRANSFORMS)
        return [
            (ix, transforms[str(h)])
            for ix, h in enumerate(self.headers) if str(h) in transforms.keys()
        ]

    def column(self, ix):
        return [r[ix] for r in self.data]

    def process(self):
        start_time = time()

        self.process_columns()
        self.process_rows()

        logger.info("Explorer Query Processing took %sms." % ((time() - start_time) * 1000))

    def process_columns(self):
        for ix in self._get_numerics():
            self.headers[ix].add_summary(self.column(ix))

    def process_rows(self):
        transforms = self._get_transforms()
        if transforms:
            for r in self.data:
                for ix, t in transforms:
                    r[ix] = t.format(str(r[ix]))

    def execute_query(self):
        cursor = self.connection.cursor()
        start_time = time()

        try:
            with transaction.atomic(self.connection.alias):
                cursor.execute(self.sql)
        except DatabaseError as e:
            cursor.close()
            raise e

        return cursor, ((time() - start_time) * 1000)


class ColumnHeader:

    def __init__(self, title):
        self.title = title.strip()
        self.summary = None

    def add_summary(self, column):
        self.summary = ColumnSummary(self, column)

    def __str__(self):
        return self.title


class ColumnStat:

    def __init__(self, label, statfn, precision=2, handles_null=False):
        self.label = label
        self.statfn = statfn
        self.precision = precision
        self.handles_null = handles_null

    def __call__(self, coldata):
        self.value = round(
            float(self.statfn(coldata)), self.precision
        ) if coldata else 0

    def __str__(self):
        return self.label


class ColumnSummary:

    def __init__(self, header, col):
        self._header = header
        self._stats = [
            ColumnStat("Sum", sum),
            ColumnStat("Avg", lambda x: float(sum(x)) / float(len(x))),
            ColumnStat("Min", min),
            ColumnStat("Max", max),
            ColumnStat("NUL", lambda x: int(sum(map(lambda y: 1 if y is None else 0, x))), 0, True)
        ]
        without_nulls = list(map(lambda x: 0 if x is None else x, col))

        for stat in self._stats:
            stat(col) if stat.handles_null else stat(without_nulls)

    @property
    def stats(self):
        return {c.label: c.value for c in self._stats}

    def __str__(self):
        return str(self._header)

explorer/views/query.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import View

from explorer import app_settings
from explorer.forms import QueryForm
from explorer.models import Query, QueryLog, MSG_FAILED_BLACKLIST
from explorer.utils import (
    url_get_query_id, url_get_log_id, url_get_show,
    url_get_rows, url_get_fullscreen, url_get_params
)
from explorer.views.auth import PermissionRequiredMixin
from explorer.views.mixins import ExplorerContextMixin
from explorer.views.utils import query_viewmodel

from django.utils.translation import gettext_lazy as _ 

class PlayQueryView(PermissionRequiredMixin, ExplorerContextMixin, View):

    permission_required = 'change_permission'

    def get(self, request):
        if url_get_query_id(request):
            query = get_object_or_404(Query, pk=url_get_query_id(request))
            return self.render_with_sql(request, query, run_query=False)

        if url_get_log_id(request):
            log = get_object_or_404(QueryLog, pk=url_get_log_id(request))
            c = log.connection or ''
            query = Query(sql=log.sql, title="Playground", connection=c)
            return self.render_with_sql(request, query)

        return self.render()

    def post(self, request):
        c = request.POST.get('connection', '')
        show = url_get_show(request)
        sql = request.POST.get('sql', '')

        query = Query(sql=sql, title="Playground", connection=c)

        passes_blacklist, failing_words = query.passes_blacklist()

        error = MSG_FAILED_BLACKLIST % ', '.join(
            failing_words
        ) if not passes_blacklist else None

        run_query = not bool(error) if show else False
        return self.render_with_sql(
            request,
            query,
            run_query=run_query,
            error=error
        )

    def render(self):
        return self.render_template(
            'explorer/play.html',
            {
                'title': 'Playground',
                'form': QueryForm()
            }
        )

    def render_with_sql(self, request, query, run_query=True, error=None):
        rows = url_get_rows(request)
        fullscreen = url_get_fullscreen(request)
        template = 'fullscreen' if fullscreen else 'play'
        form = QueryForm(
            request.POST if len(request.POST) else None,
            instance=query
        )
        return self.render_template(
            f'explorer/{template}.html',
            query_viewmodel(
                request,
                query,
                title="Playground",
                run_query=run_query,
                error=error,
                rows=rows,
                form=form
            )
        )


class QueryView(PermissionRequiredMixin, ExplorerContextMixin, View):

    permission_required = 'view_permission'

    def get(self, request, query_id):
        query, form = QueryView.get_instance_and_form(request, query_id)
        query.save()  # updates the modified date
        show = url_get_show(request)
        rows = url_get_rows(request)
        vm = query_viewmodel(
            request,
            query,
            form=form,
            run_query=show,
            rows=rows
        )
        fullscreen = url_get_fullscreen(request)
        template = 'fullscreen' if fullscreen else 'query'
        return self.render_template(
            f'explorer/{template}.html', vm
        )

    def post(self, request, query_id):
        if not app_settings.EXPLORER_PERMISSION_CHANGE(request):
            return HttpResponseRedirect(
                reverse_lazy('query_detail', kwargs={'query_id': query_id})
            )
        show = url_get_show(request)
        query, form = QueryView.get_instance_and_form(request, query_id)
        success = form.is_valid() and form.save()
        vm = query_viewmodel(
            request,
            query,
            form=form,
            run_query=show,
            rows=url_get_rows(request),
            message=_("Query saved.") if success else None
        )
        return self.render_template('explorer/query.html', vm)

    @staticmethod
    def get_instance_and_form(request, query_id):
        query = get_object_or_404(Query, pk=query_id)
        query.params = url_get_params(request)
        form = QueryForm(
            request.POST if len(request.POST) else None,
            instance=query
        )
        return query, form

explorer/views/schema.py
# -*- coding: utf-8 -*-
from django.http import Http404
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.clickjacking import xframe_options_sameorigin

from explorer.connections import connections
from explorer.schema import schema_info
from explorer.views.auth import PermissionRequiredMixin


class SchemaView(PermissionRequiredMixin, View):

    permission_required = 'change_permission'

    @method_decorator(xframe_options_sameorigin)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        connection = kwargs.get('connection', '')
        if connection not in connections:
            raise Http404
        schema = schema_info(connection)
        if schema:
            return render(
                request,
                'explorer/schema.html',
                {'schema': schema_info(connection)}
            )
        else:
            return render(request, 'explorer/schema_building.html')

explorer/templates/explorer/base.html
{% load i18n static %}

<!DOCTYPE html>
<html>
    <head>
        <base href="./">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="description" content="{{ app_name }}">
        <meta name="author" content="{{app_name}}">
        <meta name="keyword" content="{{ app_name }}">
        <title>{% block head_title %}{{ app_name }}{% endblock %}</title>
        
        <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <link href="{% static 'coreui/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'coreui/vendors/coreui/chartjs/css/coreui-chartjs.css' %}" rel="stylesheet">
    
        {% block more-css %}
        {% endblock more-css %}

    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans "SQL Explorer" %}{% if query %} - {{ query.title }}{% elif title %} - {{ title }}{% endif %}</title>

    <link rel="stylesheet" href="{% static 'explorer/css/codemirror.min.css' %}" />
    <link rel="stylesheet" href="{% static 'explorer/css/pivot.min.css' %}" />
    <link rel="stylesheet" href="{% static 'explorer/css/explorer.css' %}" />

    <script src="{% static 'explorer/js/jquery.min.js' %}"></script>
    <script src="{% static 'explorer/js/jquery.cookie.min.js' %}"></script>

    <script src="{% static 'explorer/js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript">
        queryId = "{% firstof query.id 'new' %}";
        csrfCookieName = "{% firstof csrf_cookie_name 'csrftoken' %}"
    </script>
    <script src="{% static 'explorer/js/explorer.js' %}"></script>


</head>

<body   class="c-app c-no-layout-transition {% if request.session.uitheme == 'DARK' %} c-dark-theme {% endif %} ">


    <!-- sidebar -->
    {% block sidebar %}
    {% include 'explorer/sidebar.html' %}
    {% endblock sidebar %}
    <!-- sidebar end-->


    <div class="c-wrapper">
        <!-- topbar -->
        {% block base_header %}
        {% include 'header.html' %}
        {% endblock base_header %}
        <!-- topbar end-->
        {% include 'messages.html' %}
    
        <div   class="h-100" style="overflow-x:auto">
          <div>
            
            {% comment %} {% for key, value in request.session.items %}
              {{key}} :: {{value}}<br/>
             {% endfor %}
            <hr />
            {% for key in request.COOKIES %}
            {{key}} ::<br/>
           {% endfor %}        {% endcomment %}
    
    
          </div>
          {% block sql_explorer_content_takeover %}
          <div id="wrap" class="wrap">
           
               
                  <div class="starter-template">
                      {% block sql_explorer_content %}{% endblock %}
                  </div>
               
          </div>
        {% endblock %}
        
        </div>
    
        {% block footer %}
        <footer class="c-footer">
            <div><a href="">{{app_name}}</a> © 2020.</div>
            <div class="mfs-auto">{% trans "Powered by" %}&nbsp;<a href="http://{{powered_by}}">{{powered_by}}</a></div>
        </footer>
        {% endblock footer %}

    </div>
   

   
    <script src="{% static 'explorer/js/underscore-min.js' %}"></script>
    <script src="{% static 'explorer/js/list.min.js' %}"></script>
    <script src="{% static 'explorer/js/codemirror.min.js' %}"></script>
    <script src="{% static 'explorer/js/sql.min.js' %}"></script>
    <script src="{% static 'explorer/js/comment.min.js' %}"></script>
    <script src="{% static 'explorer/js/jquery.floatThead.min.js' %}"></script>
    <script src="{% static 'explorer/js/pivot.min.js' %}"></script>
    {% block sql_explorer_scripts %}{% endblock %}
</body>

</html>

explorer/templates/explorer/export_buttons.html
{% for key, name in exporters %}
    {% if query and query.id %}
        {% if query.params %}
            <a class="btn btn-secondary" href="{% url 'download_query' query.id %}?format={{ key }}&params={{ query.params_for_url }}">{{ name }}</a>
        {% else %}
            <a class="btn btn-secondary"  href="{% url 'download_query' query.id %}?format={{ key }}">{{ name }}</a>
        {% endif %}
    {% else %}
       <input class="btn btn-secondary" type="submit" value="{{ name }}" data-format="{{ key }}" class="download-button btn btn-link" />
    {% endif %}
{% endfor %}

explorer/templates/explorer/params.html
{% if params %}
<div class="panel-footer">
    <div class="form-inline">
        {% for k, v in params.items %}
            <div class="form-group">
                <label for="{{ k }}_param" class="control-label col-sm-4">{{ k }}:</label>
                <div class="col-sm-7">
                    <input type="text" data-param="{{ k }}" class="param form-control" name="{{ k }}_param" id="{{ k }}_param" placeholder="parameter" value="{{ v }}" />
                </div>
                <div class="col-sm-1"></div>
            </div>
        {% endfor %}
    </div>
</div>
{% endif %}

explorer/templates/explorer/pdf_template.html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
    <table>
        <thead>
            <tr>
                {% for h in headers %}
                    <th>{{ h }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data %}
            <tr>
                {% for col in row %}
                    <td>{{ col }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

explorer/templates/explorer/query.html
{% extends "explorer/base.html" %}
{% load explorer_tags i18n %}

{% block sql_explorer_navlinks %}

{% endblock %}

{% block sql_explorer_content %}

 
<div class="container-fluid">
    <div class="row mt-2">
        <div class="col">
            <div class="card">
                <div class="card-header"> 
                    {% spaceless %}
                   
                        {% if query %}
                            {{ query.title }}
                            {% if shared %}<small>&nbsp;&nbsp;shared</small>{% endif %}
                        {% else %}
                            {% trans "New Query" %}
                        {% endif %}
                     
                {% endspaceless %}
                </div>

                <div class="card-body">
<div class="row">
    <div id="query_area" class="query-area col-md-12">
  
        {% if query %}
            <div class="text-right">
                <a href="{% url 'explorer_logs' %}?query_id={{ query.id }}">
                    <h2 class="small">{% trans "History" %}</h2>
                </a>
            </div>
        {% endif %}
        {% if message %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
        <div>
            {% if query %}
                <form role="form" class="form-horizontal" action="{% url 'query_detail' query.id %}" method="post" id="editor">{% csrf_token %}
            {% else %}
                <form role="form" class="form-horizontal" action="{% url 'query_create' %}" method="post" id="editor">{% csrf_token %}
            {% endif %}
                {% if error %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endif %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {% if form.title.errors %}{% for error in form.title.errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}{% endif %}
                    <label for="id_title" class="col-sm-2 control-label">{% trans "Title" %}</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="id_title" maxlength="255" name="title" type="text" {% if not can_change %}disabled{% endif %} value="{{ form.title.value|default_if_none:"" }}" />
                    </div>
                {% if form.connections|length > 1 and can_change %}
                </div>
                <div class="form-group">
                    <label for="id_connection" class="col-sm-2 control-label">{% trans "Connection" %}</label>
                    <div class="col-sm-10">
                        {{ form.connection }}
                    </div>
                {% else %}
                    {# still need to submit the connection, just hide the UI element #}
                    <div class="d-none">
                      {{ form.connection }}
                    </div>
                {% endif %}
                </div>
                <div class="form-group">
                    {% if form.description.errors %}
                        <div class="alert alert-danger">{{ form.description.errors }}</div>
                    {% endif %}
                    <label for="id_description" class="col-sm-2 control-label">
                        {% trans "Description"%}
                    </label>
                    <div class="col-sm-10">
                        <textarea
                            id="id_description" class="form-control" cols="40" name="description"
                            {% if not can_change %}disabled{% endif %} rows="2"
                        >{{ form.description.value|default_if_none:"" }}</textarea>
                    </div>
                </div>
                <input type="hidden" id="id_created_by_user" name="created_by_user" value="{{ form.created_by_user_email }}" />
                {% if form.sql.errors %}
                    {% for error in form.sql.errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}
                {% endif %}
                <div class="panel panel-default sql-panel">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-md-6">
                                <span class="panel-title">SQL</span>
                            </div>
                            <div class="col-md-6 text-right">
                                {% if query %}
                                    <small>
                                        <a href="#" title="Open in playground" id="playground_button">
                                            {% trans "Open in playground" %}
                                        </a>
                                    </small>
                                    
                                    <button id="sql_toggle" class="btn btn-lin" type="button" >
                                    <svg class="c-icon">
                                        <use xlink:href="{{STATIC_URL}}coreui/vendors/coreui/icons/svg/free.svg#cil-fullscreen "></use>
                                    </svg>
                                </button>
                                       
                                     
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="panel-content">
                        <textarea
                            class="form-control" {% if not can_change %} disabled {% endif %} cols="40" id="id_sql"
                            name="sql" rows="20">{{ form.sql.value|default_if_none:"" }}</textarea>
                    </div>
                    {% if params %}
                        {% include 'explorer/params.html' %}
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="text-center">
                        {% if can_change %}

                    <div class="btn-group" role="group">
                                <input type="submit" value="{% trans 'Save & Run' %}" class="btn btn-primary" id="save_button" />
                              
                                     {% export_buttons query %}
                                  
                                        <input type="submit" value="{% trans 'Save Only' %}" class="btn btn-secondary" id="save_only"/>
                                   
                                </ul>
                            </div>

                            <button type="button" class="btn btn-default" id="format_button">
                                {% trans "Format" %}
                            </button>
                            <button type="button" class="btn btn-default" id="show_schema_button">
                                {% trans "Show Schema" %}
                            </button>
                            <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">
                                {% trans "Hide Schema" %}
                            </button>
                        {% else %}
                            <input id="refresh_button" type="submit" value="{% trans 'Refresh' %}" class="btn btn-default" />
                            <div class="btn-group">
                                <label class="btn btn-default" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {% trans "Download" %}
                                </label>
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">{% trans "Toggle Dropdown" %}</span>
                                </button>
                                <ul class="dropdown-menu">
                                    {% export_buttons query %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="" height="828px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>

{% include 'explorer/preview_pane.html' %}

<div class="row">
    <div class="col-md-6">
        {% if query and can_change and tasks_enabled %}
            {{ form.snapshot }} {% blocktrans %}Snapshot{% endblocktrans %}
        {% endif %}
    </div>
    <div class="col-md-6 text-right">
        <small>
            {% if query.avg_duration %}
                {% blocktrans trimmed with avg_duration=query.avg_duration user_email=form.created_by_user_email created=form.created_at_time %}
                    Avg. execution: {{ avg_duration|floatformat:2 }}ms. Query created by {{ user_email }} on {{ created }}.
                {% endblocktrans %}
            {% endif %}
        </small>
    </div>
</div>


</div>
</div>
</div>
</div>
</div>
{% endblock %}

{% block sql_explorer_scripts %}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId);

            $('#sql_toggle').on('click', function () {
                $('.panel-content').slideToggle('slow');

                if ($(this).hasClass('glyphicon-resize-full')) {
                    $(this).addClass('glyphicon-resize-small').removeClass('glyphicon-resize-full');
                } else {
                    $(this).addClass('glyphicon-resize-full').removeClass('glyphicon-resize-small');
                }

            })
            {% comment %} {% if query %}
                $('.panel-content').hide();
            {% endif %} {% endcomment %}
        });
    </script>
{% endblock %}